---
- name: reload named
  ansible.builtin.service:
    name: "{{ bind_service }}"
    state: reloaded

- name: restart named
  ansible.builtin.service:
    name: "{{ bind_service }}"
    state: restarted